namespace HydrusSharp.Core.Enums
{
    public enum SortFilesBy
    {
        SORT_FILES_BY_FILESIZE = 0,
        SORT_FILES_BY_DURATION = 1,
        SORT_FILES_BY_IMPORT_TIME = 2,
        SORT_FILES_BY_MIME = 3,
        SORT_FILES_BY_RANDOM = 4,
        SORT_FILES_BY_WIDTH = 5,
        SORT_FILES_BY_HEIGHT = 6,
        SORT_FILES_BY_RATIO = 7,
        SORT_FILES_BY_NUM_PIXELS = 8,
        SORT_FILES_BY_NUM_TAGS = 9,
        SORT_FILES_BY_MEDIA_VIEWS = 10,
        SORT_FILES_BY_MEDIA_VIEWTIME = 11,
        SORT_FILES_BY_APPROX_BITRATE = 12,
        SORT_FILES_BY_HAS_AUDIO = 13,
        SORT_FILES_BY_FILE_MODIFIED_TIMESTAMP = 14,
        SORT_FILES_BY_FRAMERATE = 15,
        SORT_FILES_BY_NUM_FRAMES = 16,
        SORT_FILES_BY_NUM_COLLECTION_FILES = 17,
        SORT_FILES_BY_LAST_VIEWED_TIME = 18,
        SORT_FILES_BY_ARCHIVED_TIMESTAMP = 19,
        SORT_FILES_BY_HASH = 20
    }
}